export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const ADD_FARM_PENDING = 'ADD_FARM_PENDING';
export const ADD_FARM_SUCCESS = 'ADD_FARM_SUCCESS';
export const ADD_FARM_FAIL = 'ADD_FARM_FAIL';

export const ADD_PADDOCK_PENDING = 'ADD_PADDOCK_PENDING';
export const ADD_PADDOCK_SUCCESS = 'ADD_PADDOCK_SUCCESS';
export const ADD_PADDOCK_FAIL = 'ADD_PADDOCK_FAIL';

export const ADD_ANIMAL_PENDING = 'ADD_ANIMAL_PENDING';
export const ADD_ANIMAL_SUCCESS = 'ADD_ANIMAL_SUCCESS';
export const ADD_ANIMAL_FAIL = 'ADD_ANIMAL_FAIL';

export const ADD_RAINFALL_PENDING = 'ADD_RAINFALL_PENDING';
export const ADD_RAINFALL_SUCCESS = 'ADD_RAINFALL_SUCCESS';
export const ADD_RAINFALL_FAIL = 'ADD_RAINFALL_FAIL';

export const ADD_TALLY_PENDING = 'ADD_TALLY_PENDING';
export const ADD_TALLY_SUCCESS = 'ADD_TALLY_SUCCESS';
export const ADD_TALLY_FAIL = 'ADD_TALLY_FAIL';